/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Teacher.ViewTeacherReportJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class DoctorMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherMainJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    Organization organization;
    private UserAccount account;
    
    public DoctorMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;  
        this.organization = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReportsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageBehavioralBtn = new javax.swing.JButton();
        manageBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        viewReportsBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewReportsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/Reports.png"))); // NOI18N
        viewReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Doctor");

        manageBehavioralBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageBehavioralBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/quiz.png"))); // NOI18N
        manageBehavioralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBehavioralBtnActionPerformed(evt);
            }
        });

        manageBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/ADHD Children.png"))); // NOI18N
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manageBtn)
                    .addComponent(viewReportsBtn)
                    .addComponent(manageBehavioralBtn)
                    .addComponent(jLabel1))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(manageBtn)
                .addGap(38, 38, 38)
                .addComponent(viewReportsBtn)
                .addGap(43, 43, 43)
                .addComponent(manageBehavioralBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsBtnActionPerformed
        ViewDoctorReportJPanel viewDoctorReportJPanel = new ViewDoctorReportJPanel(userProcessContainer, business, account, business.getOrganizationDirectory());
        userProcessContainer.add("viewDoctorReportJPanel", viewDoctorReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportsBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        ManagePatientsJPanel managePatientsJPanel = new ManagePatientsJPanel(userProcessContainer, account, business, business.getOrganizationDirectory());
        userProcessContainer.add("managePatientsJPanel", managePatientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBtnActionPerformed

    private void manageBehavioralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBehavioralBtnActionPerformed
        ViewTeacherReportJPanel viewTeacherReportJPanel = new ViewTeacherReportJPanel(userProcessContainer, business, account, business.getOrganizationDirectory());
        userProcessContainer.add("viewTeacherReportJPanel", viewTeacherReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBehavioralBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageBehavioralBtn;
    private javax.swing.JButton manageBtn;
    private javax.swing.JButton viewReportsBtn;
    // End of variables declaration//GEN-END:variables
}
