/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SchoolAdmin;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.People.People;
import Business.Role.Role;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class ManageTeachersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTeachersJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    Organization organization;
    java.util.Date date;
    
    public ManageTeachersJPanel(JPanel userProcessContainer, Organization organization, EcoSystem business) {
        initComponents();
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.business = business; 
        date = new java.util.Date();
        roleComboBox.removeAllItems();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) teacherTable.getModel();
        
        model.setRowCount(0);
        
        for (People people : organization.getPeopleDirectory().getPeopleList())
        {
            Object[] row = new Object[3];
            row[0] = people.getId();
            row[1] = people.getName();
            row[2] = date;
            model.addRow(row);
        }
    }
    
    private void populateComboBox()
    {
        teacherComboBox.removeAllItems();
        
        for (People people : organization.getPeopleDirectory().getPeopleList()){
            teacherComboBox.addItem(people);
        }     
    }
    
    private void populateRoleComboBox()
    {
        roleComboBox.removeAllItems();
        for (Role role : organization.getPeopleRole()){
            roleComboBox.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Teachers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        teacherNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teacherComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        roleComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Teachers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Teachers.setText("School Administrator");
        add(Teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Teacher", "Date Added"
            }
        ));
        jScrollPane1.setViewportView(teacherTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 429, 183));
        add(teacherNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 191, -1));

        jLabel1.setText("Teacher Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 203, -1));

        jLabel3.setText("User Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/Add Teacher.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 48));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 203, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Add Teacher:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        teacherComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        teacherComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherComboBoxActionPerformed(evt);
            }
        });
        add(teacherComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 203, -1));

        jLabel6.setText("Select Teacher:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        createBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/create.png"))); // NOI18N
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 191, -1));

        jLabel7.setText("Role: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String name = teacherNameTxt.getText();     
        organization.getPeopleDirectory().createPeople(name);       
        populateTable();
        populateComboBox();
        populateRoleComboBox();// TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void teacherComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherComboBoxActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        String userName = userNameTxt.getText();
        String password = passwordTxt.getText();
        
        People people = (People) teacherComboBox.getSelectedItem();
        Role role = (Role) roleComboBox.getSelectedItem();

        organization.getUserAccountDirectory().createUserAccount(userName, password, null, people, role);

        JOptionPane.showMessageDialog(null, "Teacher Account added successfully.");
        userNameTxt.setText("");
        passwordTxt.setText("");          
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Teachers;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JComboBox teacherComboBox;
    private javax.swing.JTextField teacherNameTxt;
    private javax.swing.JTable teacherTable;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
