/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChildQuiz.Quizes;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Rewards.YouTubeViewer1;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class BehavioralQuiz extends javax.swing.JPanel {

    /**
     * Creates new form BehavioralQuiz
     */
    JPanel userProcessContainer;
    EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private YouTubeViewer1 youtubeViewer;
    ButtonGroup bg1;
    ButtonGroup bg2;
    ButtonGroup bg3;
    ButtonGroup bg4;
    ButtonGroup bg5;
    
    public BehavioralQuiz(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;    
        this.userAccount = userAccount;
        this.organization = organization;
        System.out.println("Child Name: "+userAccount.getChild().getName());
        initialize();
    }
    
    private void initialize()
    {
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        bg3 = new ButtonGroup();
        bg4 = new ButtonGroup();
        bg5 = new ButtonGroup();
        
        bg1.add(YesRad1);
        bg1.add(NoRad1);
        
        bg2.add(YesRad2);
        bg2.add(NoRad2);
        
        bg3.add(YesRad3);
        bg3.add(NoRad3);
        
        bg4.add(YesRad4);
        bg4.add(NoRad4);
        
        bg5.add(YesRad5);
        bg5.add(NoRad5);
        
        Q1Label.setName("Did you try a new task today ?");
        Q2Label.setName("Did you feel anxious or nervous at any point of the day?");
        Q3Label.setName("Did you feel sad or depressed at any point in the day?");
        Q4Label.setName("Did you spend time with your friends today?");
        Q5Label.setName("Did you get a minimum of 8 hours of sleep last night?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Q1Label = new javax.swing.JLabel();
        NoRad1 = new javax.swing.JRadioButton();
        YesRad1 = new javax.swing.JRadioButton();
        Q2Label = new javax.swing.JLabel();
        YesRad2 = new javax.swing.JRadioButton();
        NoRad2 = new javax.swing.JRadioButton();
        Q3Label = new javax.swing.JLabel();
        YesRad3 = new javax.swing.JRadioButton();
        NoRad3 = new javax.swing.JRadioButton();
        Q4Label = new javax.swing.JLabel();
        YesRad4 = new javax.swing.JRadioButton();
        NoRad4 = new javax.swing.JRadioButton();
        Q5Label = new javax.swing.JLabel();
        YesRad5 = new javax.swing.JRadioButton();
        NoRad5 = new javax.swing.JRadioButton();
        SubmitBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("BEHAVIORAL QUIZ");

        Q1Label.setText("1. Did you try a new task today ?");

        NoRad1.setBackground(new java.awt.Color(255, 255, 255));
        NoRad1.setText("No");
        NoRad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRad1ActionPerformed(evt);
            }
        });

        YesRad1.setBackground(new java.awt.Color(255, 255, 255));
        YesRad1.setText("Yes");
        YesRad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRad1ActionPerformed(evt);
            }
        });

        Q2Label.setText("2. Did you feel anxious or nervous at any point of the day ?");

        YesRad2.setBackground(new java.awt.Color(255, 255, 255));
        YesRad2.setText("Yes");
        YesRad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRad2ActionPerformed(evt);
            }
        });

        NoRad2.setBackground(new java.awt.Color(255, 255, 255));
        NoRad2.setText("No");
        NoRad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRad2ActionPerformed(evt);
            }
        });

        Q3Label.setText("3. Did you feel sad or depressed at any point in the day ?");

        YesRad3.setBackground(new java.awt.Color(255, 255, 255));
        YesRad3.setText("Yes");
        YesRad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRad3ActionPerformed(evt);
            }
        });

        NoRad3.setBackground(new java.awt.Color(255, 255, 255));
        NoRad3.setText("No");
        NoRad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRad3ActionPerformed(evt);
            }
        });

        Q4Label.setText("4. Did you spend time with your friends today?");

        YesRad4.setBackground(new java.awt.Color(255, 255, 255));
        YesRad4.setText("Yes");
        YesRad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRad4ActionPerformed(evt);
            }
        });

        NoRad4.setBackground(new java.awt.Color(255, 255, 255));
        NoRad4.setText("No");
        NoRad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRad4ActionPerformed(evt);
            }
        });

        Q5Label.setText("5.Did you get a minimum of 8 hours of sleep last night ?");

        YesRad5.setBackground(new java.awt.Color(255, 255, 255));
        YesRad5.setText("Yes");
        YesRad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRad5ActionPerformed(evt);
            }
        });

        NoRad5.setBackground(new java.awt.Color(255, 255, 255));
        NoRad5.setText("No");
        NoRad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRad5ActionPerformed(evt);
            }
        });

        SubmitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/submit.png"))); // NOI18N
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/reset UI.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(YesRad2)
                        .addGap(82, 82, 82)
                        .addComponent(NoRad2))
                    .addComponent(Q3Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(YesRad3)
                        .addGap(92, 92, 92)
                        .addComponent(NoRad3))
                    .addComponent(Q4Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(YesRad4)
                        .addGap(91, 91, 91)
                        .addComponent(NoRad4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(YesRad1)
                        .addGap(94, 94, 94)
                        .addComponent(NoRad1))
                    .addComponent(Q1Label)
                    .addComponent(Q2Label)
                    .addComponent(Q5Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesRad5)
                                .addGap(91, 91, 91)
                                .addComponent(NoRad5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubmitBtn)
                                .addGap(86, 86, 86)
                                .addComponent(jButton1)))))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(37, 37, 37)
                .addComponent(Q1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad1)
                    .addComponent(NoRad1))
                .addGap(15, 15, 15)
                .addComponent(Q2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad2)
                    .addComponent(NoRad2))
                .addGap(18, 18, 18)
                .addComponent(Q3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad3)
                    .addComponent(NoRad3))
                .addGap(18, 18, 18)
                .addComponent(Q4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad4)
                    .addComponent(NoRad4))
                .addGap(18, 18, 18)
                .addComponent(Q5Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad5)
                    .addComponent(NoRad5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(SubmitBtn))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NoRad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRad1ActionPerformed

    private void YesRad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRad1ActionPerformed

    private void YesRad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRad2ActionPerformed

    private void NoRad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRad2ActionPerformed

    private void YesRad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRad3ActionPerformed

    private void NoRad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRad3ActionPerformed

    private void YesRad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRad4ActionPerformed

    private void NoRad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRad4ActionPerformed

    private void YesRad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRad5ActionPerformed

    private void NoRad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRad5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        YesRad1.setSelected(false);
        YesRad2.setSelected(false);
        YesRad3.setSelected(false);
        YesRad4.setSelected(false);
        YesRad5.setSelected(false);
        NoRad1.setSelected(false);
        NoRad2.setSelected(false);
        NoRad3.setSelected(false);
        NoRad4.setSelected(false);
        NoRad5.setSelected(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        userAccount.getChild().getBqd().createQuestion(1, Q1Label.getName(), YesRad1.isSelected() ? "Yes" : "No");
        userAccount.getChild().getBqd().createQuestion(2, Q2Label.getName(), YesRad2.isSelected() ? "Yes" : "No");
        userAccount.getChild().getBqd().createQuestion(3, Q3Label.getName(), YesRad3.isSelected() ? "Yes" : "No");
        userAccount.getChild().getBqd().createQuestion(4, Q4Label.getName(), YesRad4.isSelected() ? "Yes" : "No");
        userAccount.getChild().getBqd().createQuestion(5, Q5Label.getName(), YesRad5.isSelected() ? "Yes" : "No");
        
        int input = JOptionPane.showOptionDialog(null, "Yaaay! Great Job!", "Here's your Reward.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        if(input == JOptionPane.OK_OPTION)
        {
            this.youtubeViewer = new YouTubeViewer1();
            String[] arguments = new String[] {"Hello"};
            try
            {
                youtubeViewer.main(arguments);     
            }
            catch (java.lang.IllegalStateException e)
            {
                System.out.println("java.lang.IllegalStateException Caught."); 
            }
        }       

        
        //JOptionPane.showMessageDialog(backBtn, "Great Job! Here's your Reward.");
    }//GEN-LAST:event_SubmitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NoRad1;
    private javax.swing.JRadioButton NoRad2;
    private javax.swing.JRadioButton NoRad3;
    private javax.swing.JRadioButton NoRad4;
    private javax.swing.JRadioButton NoRad5;
    private javax.swing.JLabel Q1Label;
    private javax.swing.JLabel Q2Label;
    private javax.swing.JLabel Q3Label;
    private javax.swing.JLabel Q4Label;
    private javax.swing.JLabel Q5Label;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JRadioButton YesRad1;
    private javax.swing.JRadioButton YesRad2;
    private javax.swing.JRadioButton YesRad3;
    private javax.swing.JRadioButton YesRad4;
    private javax.swing.JRadioButton YesRad5;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
