/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChildQuiz.Quizes;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Rewards.YouTubeViewer1;
import UserInterface.Rewards.YouTubeViewer2;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class MommyQuiz extends javax.swing.JPanel {

    /**
     * Creates new form MommyQuiz
     */
    JPanel userProcessContainer;
    EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private YouTubeViewer2 youtubeViewer;
    ButtonGroup bg1;
    ButtonGroup bg2;
    
    public MommyQuiz(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;    
        this.userAccount = userAccount;
        this.organization = organization;
        
        initialize();
    }
    
    private void initialize()
    {
        bg1 = new ButtonGroup();
        bg2 = new ButtonGroup();
        
        bg1.add(YesRad1);
        bg1.add(NoRad1);
        
        bg2.add(YesRad2);
        bg2.add(NoRad2);
        
        String task1 = new String();
        String task2 = new String();
        
        try
        {
            task1 = userAccount.getChild().getMqd().getQuestions().get(0).gettask();
            task2 = userAccount.getChild().getMqd().getQuestions().get(1).gettask();
        }
        catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(backBtn, "No tasks from mommy yet. Yaaaay!");
        }
        
        task1Label.setText(task1.isEmpty() ? "No Task from Mommy yet" : task1);
        task2Label.setText(task2.isEmpty() ? "No Task from Mommy yet" : task2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        task1Label = new javax.swing.JLabel();
        task2Label = new javax.swing.JLabel();
        YesRad1 = new javax.swing.JRadioButton();
        NoRad1 = new javax.swing.JRadioButton();
        NoRad2 = new javax.swing.JRadioButton();
        YesRad2 = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Mommy Asks");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Task 1:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Task 2:");

        task1Label.setText("jLabel4");

        task2Label.setText("jLabel4");

        YesRad1.setBackground(new java.awt.Color(255, 255, 255));
        YesRad1.setText("Yes");

        NoRad1.setBackground(new java.awt.Color(255, 255, 255));
        NoRad1.setText("No");

        NoRad2.setBackground(new java.awt.Color(255, 255, 255));
        NoRad2.setText("No");

        YesRad2.setBackground(new java.awt.Color(255, 255, 255));
        YesRad2.setText("Yes");

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/submit.png"))); // NOI18N
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(backBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(task2Label)
                                    .addComponent(task1Label)
                                    .addComponent(submitBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesRad1)
                                .addGap(107, 107, 107)
                                .addComponent(NoRad1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesRad2)
                                .addGap(107, 107, 107)
                                .addComponent(NoRad2)))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(task1Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad1)
                    .addComponent(NoRad1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(task2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRad2)
                    .addComponent(NoRad2))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        userAccount.getChild().getMqd().getQuestions().get(0).setResponse(YesRad1.isSelected() ? "Yes" : "No");
        userAccount.getChild().getMqd().getQuestions().get(1).setResponse(YesRad2.isSelected() ? "Yes" : "No");
        
        int input = JOptionPane.showOptionDialog(null, "Yaaay! Great Job!", "Here's your Reward.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        if(input == JOptionPane.OK_OPTION)
        {
            this.youtubeViewer = new YouTubeViewer2();
            String[] arguments = new String[] {"Hello"};
            try
            {
                youtubeViewer.main(arguments);     
            }
            catch (java.lang.IllegalStateException e)
            {
                System.out.println("java.lang.IllegalStateException Caught."); 
            }     
        } 
        
//        JOptionPane.showMessageDialog(submitBtn, "Yaaay! Great Job!");
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NoRad1;
    private javax.swing.JRadioButton NoRad2;
    private javax.swing.JRadioButton YesRad1;
    private javax.swing.JRadioButton YesRad2;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel task1Label;
    private javax.swing.JLabel task2Label;
    // End of variables declaration//GEN-END:variables
}
