/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChildQuiz;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.ChildQuiz.Quizes.TeacherQuiz;
import UserInterface.ChildQuiz.Quizes.BehavioralQuiz;
import UserInterface.ChildQuiz.Quizes.MommyQuiz;
import UserInterface.SystemAdmin.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class ChildMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildMainJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    
    public ChildMainJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;    
        this.userAccount = userAccount;
        this.organization = organization;
        System.out.println("Child Name: "+userAccount.getChild().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mommyQuizBtn = new javax.swing.JButton();
        doctorQuizBtn1 = new javax.swing.JButton();
        mommyQuizBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Helloooooo!!! ");

        mommyQuizBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mommyQuizBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/family.png"))); // NOI18N
        mommyQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mommyQuizBtnActionPerformed(evt);
            }
        });

        doctorQuizBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doctorQuizBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/doctor.png"))); // NOI18N
        doctorQuizBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorQuizBtn1ActionPerformed(evt);
            }
        });

        mommyQuizBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mommyQuizBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/Teacher.png"))); // NOI18N
        mommyQuizBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mommyQuizBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mommyQuizBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mommyQuizBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorQuizBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(doctorQuizBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(mommyQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(mommyQuizBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mommyQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mommyQuizBtnActionPerformed
        MommyQuiz mommyQuiz = new MommyQuiz(userProcessContainer, userAccount, organization, business);
        userProcessContainer.add("mommyQuiz", mommyQuiz);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mommyQuizBtnActionPerformed

    private void mommyQuizBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mommyQuizBtn1ActionPerformed
        TeacherQuiz teacherQuiz = new TeacherQuiz(userProcessContainer, userAccount, organization, business);
        userProcessContainer.add("teacherQuiz", teacherQuiz);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mommyQuizBtn1ActionPerformed

    private void doctorQuizBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorQuizBtn1ActionPerformed
        BehavioralQuiz behavioralQuiz = new BehavioralQuiz(userProcessContainer, userAccount, organization, business);
        userProcessContainer.add("behavioralQuiz", behavioralQuiz);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_doctorQuizBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorQuizBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mommyQuizBtn;
    private javax.swing.JButton mommyQuizBtn1;
    // End of variables declaration//GEN-END:variables
}
