/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Teacher;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Doctor.ManagePatientsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class TeacherMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherMainJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    Organization organization;
    UserAccount account;
    
    public TeacherMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;    
        this.organization = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        manageStudentsBtn = new javax.swing.JButton();
        viewReportsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageQuizBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        manageStudentsBtn.setText("Manage ADD/ADHD Students");
        manageStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentsBtnActionPerformed(evt);
            }
        });

        viewReportsBtn.setText("View Reports");
        viewReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Teacher");

        manageQuizBtn.setText("Manage Quiz");
        manageQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageQuizBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageStudentsBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageQuizBtn)
                            .addComponent(viewReportsBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(manageStudentsBtn)
                .addGap(41, 41, 41)
                .addComponent(viewReportsBtn)
                .addGap(43, 43, 43)
                .addComponent(manageQuizBtn)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentsBtnActionPerformed
        ManageStudentsJPanel manageStudentsJPanel = new ManageStudentsJPanel(userProcessContainer, account, business, business.getOrganizationDirectory());
        userProcessContainer.add("manageStudentsJPanel", manageStudentsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStudentsBtnActionPerformed

    private void viewReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsBtnActionPerformed
        ViewTeacherReportJPanel viewTeacherReportJPanel = new ViewTeacherReportJPanel(userProcessContainer, business, account, business.getOrganizationDirectory());
        userProcessContainer.add("viewTeacherReportJPanel", viewTeacherReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportsBtnActionPerformed

    private void manageQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageQuizBtnActionPerformed
        ViewTeacherReportJPanel viewTeacherReportJPanel = new ViewTeacherReportJPanel(userProcessContainer, business, account, business.getOrganizationDirectory());
        userProcessContainer.add("viewTeacherReportJPanel", viewTeacherReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageQuizBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageQuizBtn;
    private javax.swing.JButton manageStudentsBtn;
    private javax.swing.JButton viewReportsBtn;
    // End of variables declaration//GEN-END:variables
}
