/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Parent;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.ChildQuiz.ChildMainJPanel;
import UserInterface.SystemAdmin.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josep
 */
public class ParentMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParentMainJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    
    public ParentMainJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;    
        this.userAccount = userAccount;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        viewReportsBtn = new javax.swing.JButton();
        setTasksBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();
        childModeBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        viewReportsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/Reports.png"))); // NOI18N
        viewReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsBtnActionPerformed(evt);
            }
        });

        setTasksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/set tasks.png"))); // NOI18N
        setTasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTasksBtnActionPerformed(evt);
            }
        });

        signUpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/sign-up child.png"))); // NOI18N
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        childModeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        childModeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Resources/Child mode.png"))); // NOI18N
        childModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childModeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewReportsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setTasksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(childModeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(294, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(signUpBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(viewReportsBtn)
                        .addGap(41, 41, 41)
                        .addComponent(setTasksBtn)
                        .addGap(44, 44, 44)
                        .addComponent(childModeBtn)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsBtnActionPerformed
        ParentReportJPanel parentReportJPanel = new ParentReportJPanel(userProcessContainer, business, userAccount, business.getOrganizationDirectory());
        userProcessContainer.add("parentReportJPanel", parentReportJPanel);  
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportsBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        SignUpChildJPanel signUpChildJPanel = new SignUpChildJPanel(userProcessContainer, business, userAccount, business.getOrganizationDirectory());
        userProcessContainer.add("signUpChildJPanel", signUpChildJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void childModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childModeBtnActionPerformed
        // TODO add your handling code here:
        if(userAccount.getChild().getName() == null)
        {
            JOptionPane.showMessageDialog(childModeBtn, "Please sign-up your child first");
        }
        else
        {
        ChildMainJPanel childMainJPanel = new ChildMainJPanel(userProcessContainer, userAccount, organization, business);
        userProcessContainer.add("childMainJPanel", childMainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
        }
    }//GEN-LAST:event_childModeBtnActionPerformed

    private void setTasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTasksBtnActionPerformed
        SetTaskJPanel setTaskJPanel = new SetTaskJPanel(userProcessContainer, business, userAccount, business.getOrganizationDirectory());
        userProcessContainer.add("setTaskJPanel", setTaskJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_setTasksBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton childModeBtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton setTasksBtn;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JButton viewReportsBtn;
    // End of variables declaration//GEN-END:variables
}
